//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petShopPetrou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderProduct()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public System.DateTime dateOrder { get; set; }
        public System.DateTime dateDel { get; set; }
        public int idPP { get; set; }
        public int idTown { get; set; }
        public int idStreet { get; set; }
        public Nullable<int> Home { get; set; }
        public Nullable<int> idRole { get; set; }
        public int Code { get; set; }
        public int idStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual PickPoint PickPoint { get; set; }
        public virtual Role Role { get; set; }
        public virtual Status Status { get; set; }
        public virtual Street Street { get; set; }
        public virtual Town Town { get; set; }
    }
}
