//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petShopPetrou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string Articul { get; set; }
        public int idProductName { get; set; }
        public string Price { get; set; }
        public int Sale { get; set; }
        public int idManufacturer { get; set; }
        public int idPost { get; set; }
        public int idCategory { get; set; }
        public int NowSale { get; set; }
        public int Count { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public string ImageName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Post Post { get; set; }
        public virtual ProductName ProductName { get; set; }
    }
}
